#!/bin/sh
rm -rf v0.9
git clone git://github.com/pixhawk/mavlink.git -b master v0.9
cd v0.9 && git checkout 500480af09 && rm -rf .git && cd ..
rm -rf v1.0
git clone git://github.com/pixhawk/mavlink.git -b v10release v1.0
cd v1.0 && git checkout d6bd668673 && rm -rf .git && cd ..
